project_id = "qaedjtdwishtcrfjhmvu"

[functions.smartlead-sync]
verify_jwt = false

[functions.dev-auto-login]
verify_jwt = false

[functions.replyio-sync]
verify_jwt = false

[functions.compute-patterns]
verify_jwt = false
